<a href="https://colab.research.google.com/github/kyliequinney/MachineLearning4375/blob/main/4375Assignment3/4375_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#upload dataset
import pandas as pd
import numpy as np
df = pd.read_csv('https://github.com/kyliequinney/StudentMathData/raw/refs/heads/main/NBChealth.txt', sep = '|', encoding='latin-1', header=None)
df.head()

,0,1,2
0,548617649010532353,Fri Dec 26 23:13:35 +0000 2014,Ebola Exposure?: CDC Worker 'Remains Well' http://nbcnews.to/1tmYMkv
1,548569476795731968,Fri Dec 26 20:02:09 +0000 2014,Pregnant Woman Taken Off Life Support in Ireland http://nbcnews.to/1BcYvPG
2,548533428023738368,Fri Dec 26 17:38:55 +0000 2014,Money from #IceBucketChallenge still flowing to ALS Association where leaders remain awestruck by gush of goodwill: http://ow.ly/GseY3
3,548531135442337793,Fri Dec 26 17:29:48 +0000 2014,Caramel Apples Recalled After Listeria Deaths http://nbcnews.to/1EqpPjj
4,548194819907284992,Thu Dec 25 19:13:24 +0000 2014,Ice Bucket Challenge Still Rains Bucks on ALS http://nbcnews.to/1thdMAd

In [ ]:
#drop tweet id and timestamp columns
df = df.drop(columns=[0,1])
df.head()

                                                                                                                                        2
0                                                                    Ebola Exposure?: CDC Worker 'Remains Well' http://nbcnews.to/1tmYMkv
1                                                              Pregnant Woman Taken Off Life Support in Ireland http://nbcnews.to/1BcYvPG
2  Money from #IceBucketChallenge still flowing to ALS Association where leaders remain awestruck by gush of goodwill: http://ow.ly/GseY3
3                                                                 Caramel Apples Recalled After Listeria Deaths http://nbcnews.to/1EqpPjj
4                                                                 Ice Bucket Challenge Still Rains Bucks on ALS http://nbcnews.to/1thdMAd

In [ ]:
example_with_at = df[df[2].str.contains('@')]
example_with_at

                                                                                                                                                                            2
270                              RT @JuliaSommerfeld: Tales of chucking big jobs are the new lady porn RT @ELLEmagazine: What's REALLY causing women to burn out before 30:

623                                 RT @JoyJernigan: Yuck! RT @NBCNewsTravel: Vacationer beware: Hot tubs, pools may harbor many germs  http://nbcnews.to/1qa8ROz @jeffrossen
650                                                                    FDA Warns of Dangerous #Testosterone Risks http://nbcnews.to/1isH8Ge video via @NBCNightlyNews #health
651                                                            CDC: Anthrax Exposure Resulted From Breakdown in Safety Protocol http://nbcnews.to/1isH1u8 via @NBCNightlyNews
654                           RT @TODAYshowHealth: Science of hotness: Strength, endurance and soccer  http://nbcnews.to/1ih32MV #WorldCup2014 #WorldCup http://t.co/V81o9UQ

726                              RT @NBCNightlyNews: When we come back: an increasing number of Americans are living with diabetes and millions of them dont even know it #

912                                                    RT @AkronChildrens: Our NICU is temporary home for another set of rare #monoamniotic twins!  http://nbcnews.to/1jnjESx
947                                                                          Video: TSA Warns Travelers About Deadly MERS Virus http://nbcnews.to/1mW6zNQ via @NBCNightlyNews
1103                                         RT @rehemaellis: One family uses Disney characters to communicate with their son with autism. See how tonight on @NBCNightlyNews
1120                                                      RT @NBCNewsTravel: Swiss certified as world's first allergy friendly airline http://nbcnews.to/1jHKUG3 via @hbaskas
1154  RT @NBCNews: Failing at Fertility: New 'report card' grades states on how they help  or don't http://nbcnews.to/1mwepRz http://pbs.twimg.com/media/BlwlqhCCUAAAzVW.jpg
1155                    RT @TODAYshow: .@nmoralesnbc looking great after finishing #BostonMarathon! #GoNatalieGo #BostonStrong http://pbs.twimg.com/media/Blw7LMbIMAA8oud.jpg
1184                             RT @nbcnightlynews: A New York teen is on a very personal mission to find a cure for an unusual form of cancer. @AnnCurry reports now #NBCN

1238                             RT @BreakingNews: Report: US Health Secretary Kathleen Sebelius expected to resign; announcement expected tomorrow, source tells @Bloomberg

1242                                                 RT @NBCNews: COMING UP: How safe are our schools? #AskNBCNews during a live webcast at 1:15pET http://nbcnews.to/1hvSQhY
1265            RT @nbcnightlynews: Emergency rooms see increase in heroin patients http://nbcnews.to/1oJdjnn #HeroinInAmerica http://pbs.twimg.com/media/Bks3JnuIgAEMQbc.jpg
1339                             RT @NBCNews: New research shows more kids are being bullied than previously thought. #AskNBCNews live webcast at 1:15 with more: http://t.c

1389                                                          RT @DrNancyNBCNEWS: India has done it.  3 yrs without #polio @who Time to tackle Nigeria, Pakistan, Afghanistan
1528                             RT @NBCNews: .@DrNancyNBCNews about to visit refugee camp school on live webcast. Questions? Ask using #SyriasChildren http://t.co/kg1EIjge

1550                             RT @DrNancyNBCNEWS: NICU w/ sick babies. I saw more birth defects in last few days than in my entire pediatric residency #SyriasChildren ht

1780                                                                                                                                               @PartainMike  can we talk?
1893                                                        If you haven't seen it already, check out the new @NBCNews redesign http://nbcnews.to/1jgczmp. What do you think?
1958                                                                     RT @NBCNews: Texas judge orders brain-dead pregnant woman off life support http://nbcnews.to/1e2mI1X
2011                             RT @melissadahl: Asian-Americans tend to have lower BMI, but still struggle with health issues associated with being overweight. http://t.c

2058                   RT @NBCNewsUS: Mold, mice and zip codes: Inside the childhood asthma epidemic http://nbcnews.to/1iyw4Wx http://pbs.twimg.com/media/BdC_t7fIQAAY6p_.jpg
2168                                                             RT @nytimesbusiness: Youre the Boss Blog: How I Found a Surprisingly Good Health Plan http://nyti.ms/IAbMMD
2189                                           RT @maggiemfox: You get an extra week! http://www.nbcnews.com/health/extra-week-feds-extend-healthcare-gov-deadline-2D11641454
2194                                                                                600K baby monitors recalled after 2 deaths http://nbcnews.to/1e4F6p2 via @NBCNewsBusiness
2204                                      RT @NBCNewsTravel: Too fat to travel? Man rejected by plane, train and cruise ship finally bound for home http://nbcnews.to/1b8yWWY
2207                                                    RT @NBCNewYork: Mayor Bloomberg has signed the bill raising NYC's tobacco-buying age to 21 http://4.nbcny.com/CpOn4Z4
2277     RT @DrNancyNBCNEWS: No admissions. No supplies but people still come with injuries #Tacolban @nbcnightlynews @nbcnews http://pbs.twimg.com/media/BYyvUFqCMAELcft.jpg
2355                                                             HHS @Sebelius expected to acknowledge glitches in Obamacare testimony. Story here: http://nbcnews.to/1hqDOro
2766                     RT @DrFriedenCDC: Little cigars contain the same toxic &amp; cancer-causing ingredients found in cigarettes &amp; are not a safe alternative. http:

2767                                                                       RT @Lizzyfit: Pet owners, beware of tainted jerky treats. *SAFETY ALERT* http://nbcnews.to/17eizaE
2770                             RT @DrNancyNBCNEWS: Tonight @nbcnightlynews @bwilliams women, heart disease and why everyone needs to know about defibrillators.  Easy and

2869                                                 And a big thank you to @larry_levitt from the @KaiserFamFound for taking the time to answer questions today. #AskDrNancy
2871                                                                   .@Curly_Lumpkin Income is Modified Adjusted Gross income. Similar to AGI but not exactly.  #AskDrNancy
2872                                                        RT @KaiserFamFound: Brief from KFF's @Larry_Levitt on how premium tax credits work http://ow.ly/po4GU #AskDrNancy
2873                             RT @Curly_Lumpkin: @NBCNewsHealth self employed farmer here: Is income AGI or pre-tax? Our AGI is next to zero. FL no Medicaid expansion.

2874                               .@BeganRight Also, remember that advance tax credits are estimated. You could owe more or get a refund based on actual income. #AskDrNancy
2875                                         .@BeganRight U can get the tax credit in advance to help pay your premium. You do have to file the next year though. #AskDrNancy
2876                             RT @BeganRight: #AskDrNancy If you do not pay taxes, how do you get a credit to pay premiums? I do not have extra $ for premiums or get sup

2879                               .@brandonburkman If u get a job with health insurance, you can switch and sign up for that. And vice versa if u lose your job. #AskDrNancy
2880                             RT @brandonburkman: #AskDrNancy If my wife has coverage through the Affordable Care Act, and later gets a job that offers coverage, will sh

2881                              .@GodfatherFOUR U can use your tax credit in any plan in an exchange (except a catastrophic plan). You just pay the difference. #AskDrNancy
2882                                    .@JoeTweetsALot Probably won't have much effect on cost of prescriptions. But plans will have to cover them in exchanges. #AskDrNancy
2883                                                RT @JoeTweetsALot: @nbcnightlynews @DrNancyNBCNEWS @NBCNewsHealth how will this affect cost of prescriptions? #AskDrNancy
2885                                                                              .@7Blasdel7 You can stay on your parents policy until 26, even if u have a job. #AskDrNancy
2886                             RT @7Blasdel7: #AskDrNancy Im a recent college grad, I have started a career but Im covered on my parents insurance till age26. Can I use t

2887                                      .@LORINYCGIRL It's likely you'll qualify for a tax credit. And there are special enrollment periods if u lose your job. #AskDrNancy
2888                         RT @LORINYCGIRL: @DrNancyNBCNEWS what if u lose ur job after open enrollment &amp; ur company does not have cobra cuz they're too small? #AskDr

2889                                .@nado7244  Today! U can sign up for insurance with no discrimination for pre-existing conditions. Coverage starts January 1. #AskDrNancy
2890                                             .@bradlerner I think enrollment will ramp up very slowly, so probably not much effect on wait for doctor visits. #AskDrNancy
2891                             RT @bradlerner: #AskDrNancy Any insight on how drs will handle increased demand for services-will we see longer waits for specialists, part

2892                                                  .@ConnSherrie But, starting in 2018 there will be a "cadillac" tax on high priced employer insurance plans. #AskDrNancy
2893                                                                            .@ConnSherrie You won't be taxed on what your employer pays for health insurance. #AskDrNancy
2894                             RT @ConnSherrie: #AskDrNancy If our 2014 W-2 is going to verify our employer paid health insurance ~ are we going to be taxed on it?!  #Dea

2895                                                 .@rachelmariezim There r exceptions for the individual mandate. If you're income is very low, you're exempt. #AskDrNancy
2896                             RT @rachelmariezim: If a 21 year old goes to college full time, doesn't work, and doesn't have insurance, will she be penalized for not enr

2897                                              .@Provisionfit (2 of 2) Students may have options at school. Or, they may qualify for tax credits or Medicaid. #askdrnancy.
2898                                                                           .@Provisionfit (1 of 2) Young adults can stay on their parents insurance until 26. #askdrnancy
2899                                                       RT @Provisionfit: #AskDrNancy what happens to young college students or young kids who can't afford the insurance?
2900                                                                                 .@Mwforhr The web sites are having problems. U can also call 1-800-318-2596. #AskDrNancy
2901                                           RT @Mwforhr: If people are having trouble enroll ing thru the website, what other options do they have? #obamacare #AskDrNancy
2903                                            LIVE NOW: Kaisers @Larry_Levitt answers your questions on the Affordable Care Act. Participate using the #AskDrNancy hashtag
2904                                            Questions on the Affordable Care Act? Chat live with Kaisers @Larry_Levitt at 11am ET http://nbcnews.to/1dTUuVB  #AskDrNancy
2906                                             Questions on the Affordable Care Act? Chat live with Kaisers @Larry_Levitt at 11am ET http://nbcnews.to/1dTUuVB #AskDrNancy
3017                                                             How can you cut your risk of Alzheimer's? Ask @DrNancyNBCNEWS and @mariashriver using the hashtag #AgeofAlz.
3157                                 Tomorrow, join @DrNancyNBCNEWS in a conversation about the link between wealth &amp; health. Qs? Use #inplainsight http://bit.ly/14XbwhD
3159                                                                    @aasmom411 Hi Lisa - "A healthy heart is a healthy brain," says Dr. Maria Carrillo of @alzassociation
3160                                    Think about family planning in the future - have those conversations with your loved ones now. -- Dr. Maria Carrillo, @alzassociation
3161                                                                                                      @kim_payne_1 Hey Kim! Do you have an actual question for Dr. Nancy?
3163                                  We'll be chatting with @DrNancyNBCNEWS about early Alzheimer's on Google+ at 9 a.m. ET. Join us here: http://bit.ly/145p78L #AskDrNancy
3165                             RT @DrNancyNBCNEWS: A new study tonight with an update on women and baby aspirin and the prevention of colon cancer.  What you'll want to k

3167                              Got a question for @DrNancyNBCNEWS on early Alzheimer's? Ask it with the hashtag #AskDrNancy, and she may answer tomorrow in a Google chat.
3255                             RT @DrNancyNBCNEWS: Can increased consumption of red meat increase a chance of developing type 2 diabetes?   Report in JAMA Int Med suggest

3423                                  Live Facebook chat @ 12pET.  @DrNancyNBCNEWS answers q's about preventive breast &amp; ovarian cancer treatments http://on.fb.me/ayijAu
3659                                  @HonestToddler You've been quoted in my #Storify story "'Reasons my son is crying' makes parents weep... with mirth" http://sfy.co/p4B0
3737                                          @jeffrossen You've been quoted in my #Storify story "Friends and strangers react to Jenna Wolfe's baby news" http://sfy.co/bGHK
3738                                 @EricaRHill @alroker You've been quoted in my #Storify story "Friends and strangers react to Jenna Wolfe's baby news" http://sfy.co/bGHK
3740                                                                Its a girl! @JennaWolfe &amp; @stephgosk are expecting a baby, due in August http://on.today.com/16XHV9c
3947                                                                RT @nbcnightlynews: CDC: Flu vaccine often doesnt work. @RobertBazell reports: http://nbcnews.to/15z5cOa
4005                                      RT @BrianRAlexander: My story on "ongoing, severe epidemic" of sexually transmitted infections in the US: http://nbcnews.to/12hncwE
4079                                     RT @melissadahl: BREAKING CHILDREN'S LITERATURE NEWS: Scarlet fever did *not* cause Mary Ingalls' blindness http://nbcnews.to/VE5Wj8
4144                                                   RT @maggiemfox: You didn't forget about the flu, did you? http://www.msnbc.msn.com/id/50587303/ns/health-cold_and_flu/
4206                             RT @todayshowhealth: Should Lance Armstrong's legacy be about cycling -- or about those he's inspired by  showing there is life after ca ...

In [ ]:
#remove any words that start with '@' symbol
import re

def remove_at_words(text):
  return re.sub(r'@\w+', '', text)

df[2] = df[2].apply(remove_at_words)

df.head(10)
example_with_at = df[df[2].str.contains('@')]
example_with_at

                                                                                                                             2
3423  Live Facebook chat @ 12pET.   answers q's about preventive breast &amp; ovarian cancer treatments http://on.fb.me/ayijAu

In [ ]:
example_with_hash = df[df[2].str.contains('#')]
example_with_hash

                                                                                                                                                          2
2                    Money from #IceBucketChallenge still flowing to ALS Association where leaders remain awestruck by gush of goodwill: http://ow.ly/GseY3
5                     Following mistake and possible exposures at #CDC #Ebola lab, health of involved staff to be monitored for 21 days. http://ow.ly/GpzmS
228                                                                        'Back in the Fight': American Doctor Helps #FightEbola http://nbcnews.to/1v4xXBL
650                                                                 FDA Warns of Dangerous #Testosterone Risks http://nbcnews.to/1isH8Ge video via  #health
654                         RT : Science of hotness: Strength, endurance and soccer  http://nbcnews.to/1ih32MV #WorldCup2014 #WorldCup http://t.co/V81o9UQ

726                           RT : When we come back: an increasing number of Americans are living with diabetes and millions of them dont even know it #

912                                                 RT : Our NICU is temporary home for another set of rare #monoamniotic twins!  http://nbcnews.to/1jnjESx
1155                        RT : . looking great after finishing #BostonMarathon! #GoNatalieGo #BostonStrong http://pbs.twimg.com/media/Blw7LMbIMAA8oud.jpg
1158                                                                             #SavingEliza: Sick Girl's Parents Plead for Help http://nbcnews.to/1r8ZrR5
1184                                   RT : A New York teen is on a very personal mission to find a cure for an unusual form of cancer.  reports now #NBCN

1242                                       RT : COMING UP: How safe are our schools? #AskNBCNews during a live webcast at 1:15pET http://nbcnews.to/1hvSQhY
1265         RT : Emergency rooms see increase in heroin patients http://nbcnews.to/1oJdjnn #HeroinInAmerica http://pbs.twimg.com/media/Bks3JnuIgAEMQbc.jpg
1287                                                                                 #InLabor: Twitter Employee Live-Tweets Birth http://nbcnews.to/1h3KI77
1300                                                                                       #AskNBCNews: Fort Hood Shooting Webcast http://nbcnews.to/Po153M
1313                                                                          Is Salt Healthy? Are Mammograms Useful? #AskNBCNews http://nbcnews.to/1s8H7ca
1323                                                             Is Salt Healthy? Are Mammograms Useful? #AskNBCNews at 1:15 p.m. http://nbcnews.to/1ecoOd8
1329                                                                 Mammography, Salt, Autism - #AskNBCNews' Dr. Nancy Snyderman http://nbcnews.to/1pQE9oE
1339                   RT : New research shows more kids are being bullied than previously thought. #AskNBCNews live webcast at 1:15 with more: http://t.c

1341                                                                                #AskNBCNews: Your Bullying Questions Answered http://nbcnews.to/1dNOH7Y
1354                                                                                #AskNBCNews: Obamacare Deadline Day Questions http://nbcnews.to/1oiXSlz
1357                                                                                #AskNBCNews: Obamacare Deadline Day Questions http://nbcnews.to/1hsMFcM
1363                                                                                #AskNBCNews: Obamacare Deadline Day Questions http://nbcnews.to/1jrCl5w
1389                                                           RT : India has done it.  3 yrs without #polio  Time to tackle Nigeria, Pakistan, Afghanistan
1451  My #FirstTweet: Turns out to have been the H1N1 pandemic. https://twitter.com/maggiemfox/statuses/1580629768. What was yours? http://first-tweets.com
1528                                  RT : . about to visit refugee camp school on live webcast. Questions? Ask using #SyriasChildren http://t.co/kg1EIjge

1532                                                                                Resilient #SyriasChildren Find Play, Laughter http://nbcnews.to/1lWcW6p
1545                                                                      Bioethicist: #SaveJosh? Maybe, but What About the Rest? http://nbcnews.to/1epyZe2
1550                          RT : NICU w/ sick babies. I saw more birth defects in last few days than in my entire pediatric residency #SyriasChildren ht

2277                         RT : No admissions. No supplies but people still come with injuries #Tacolban   http://pbs.twimg.com/media/BYyvUFqCMAELcft.jpg
2334                                                           Strangers surround dying man in his favorite color, #skybluepink http://on.today.com/1aF8kZO
2354                                We're sorry, and we'll fix the website, health officials promise. Story here: http://nbcnews.to/1hqIJZy #aca #Obamacare
2357                   How deep are problems w #Obamacare site, how long to fix it? Top site exec grilled at 10a http://nbcnews.to/1cgBDmz #healthinsurance
2360                                            Smokers most likely to think about quitting on Mondays, study finds http://nbcnews.to/1cdMBt1 #MustbeMonday
2869                                                           And a big thank you to  from the  for taking the time to answer questions today. #AskDrNancy
2870                  Thanks for all of the questions. If you have more, ask using the #AskDrNancy hashtag. And check out http://www.nbcnews.com/healthcare
2871                                                               . Income is Modified Adjusted Gross income. Similar to AGI but not exactly.  #AskDrNancy
2872                                                                  RT : Brief from KFF's  on how premium tax credits work http://ow.ly/po4GU #AskDrNancy
2874                        . Also, remember that advance tax credits are estimated. You could owe more or get a refund based on actual income. #AskDrNancy
2875                                  . U can get the tax credit in advance to help pay your premium. You do have to file the next year though. #AskDrNancy
2876                      RT : #AskDrNancy If you do not pay taxes, how do you get a credit to pay premiums? I do not have extra $ for premiums or get sup

2877                                                        Also, if you can't get on the Obamacare web site, u can always call 1-800-318-2596. #AskDrNancy
2878                                              Obamacare web sites are having glitches on day 1. Open enrollment lasts for 6 months, though. #AskDrNancy
2879                            . If u get a job with health insurance, you can switch and sign up for that. And vice versa if u lose your job. #AskDrNancy
2880                          RT : #AskDrNancy If my wife has coverage through the Affordable Care Act, and later gets a job that offers coverage, will sh

2881                          . U can use your tax credit in any plan in an exchange (except a catastrophic plan). You just pay the difference. #AskDrNancy
2882                                . Probably won't have much effect on cost of prescriptions. But plans will have to cover them in exchanges. #AskDrNancy
2883                                                                                        RT :    how will this affect cost of prescriptions? #AskDrNancy
2884                                              Questions on the Affordable Care Act? We're answering them now. Participate using the #AskDrNancy hashtag
2885                                                                      . You can stay on your parents policy until 26, even if u have a job. #AskDrNancy
2886                     RT : #AskDrNancy Im a recent college grad, I have started a career but Im covered on my parents insurance till age26. Can I use t

2887                                . It's likely you'll qualify for a tax credit. And there are special enrollment periods if u lose your job. #AskDrNancy
2888                                  RT :  what if u lose ur job after open enrollment &amp; ur company does not have cobra cuz they're too small? #AskDr

2889                       .  Today! U can sign up for insurance with no discrimination for pre-existing conditions. Coverage starts January 1. #AskDrNancy
2890                                      . I think enrollment will ramp up very slowly, so probably not much effect on wait for doctor visits. #AskDrNancy
2891                      RT : #AskDrNancy Any insight on how drs will handle increased demand for services-will we see longer waits for specialists, part

2892                                            . But, starting in 2018 there will be a "cadillac" tax on high priced employer insurance plans. #AskDrNancy
2893                                                                      . You won't be taxed on what your employer pays for health insurance. #AskDrNancy
2894                       RT : #AskDrNancy If our 2014 W-2 is going to verify our employer paid health insurance ~ are we going to be taxed on it?!  #Dea

2895                                              . There r exceptions for the individual mandate. If you're income is very low, you're exempt. #AskDrNancy
2897                                         . (2 of 2) Students may have options at school. Or, they may qualify for tax credits or Medicaid. #askdrnancy.
2898                                                                      . (1 of 2) Young adults can stay on their parents insurance until 26. #askdrnancy
2899                                                  RT : #AskDrNancy what happens to young college students or young kids who can't afford the insurance?
2900                                                                       . The web sites are having problems. U can also call 1-800-318-2596. #AskDrNancy
2901                                 RT : If people are having trouble enroll ing thru the website, what other options do they have? #obamacare #AskDrNancy
2902                                    Technically, you can start signing up today under Obamacare. But the web sites are having some hiccups. #askdrnancy
2903                                       LIVE NOW: Kaisers  answers your questions on the Affordable Care Act. Participate using the #AskDrNancy hashtag
2904                                       Questions on the Affordable Care Act? Chat live with Kaisers  at 11am ET http://nbcnews.to/1dTUuVB  #AskDrNancy
2906                                        Questions on the Affordable Care Act? Chat live with Kaisers  at 11am ET http://nbcnews.to/1dTUuVB #AskDrNancy
3007                Do you have questions about the role diet and exercise may play in Alzheimer's? Send them to #AgeofAlz and they may be answered on air.
3012                                                                                 How has Alzheimers impacted your family? Share your stories #AgeofAlz
3017                                                                       How can you cut your risk of Alzheimer's? Ask  and  using the hashtag #AgeofAlz.
3157                              Tomorrow, join  in a conversation about the link between wealth &amp; health. Qs? Use #inplainsight http://bit.ly/14XbwhD
3162                  And our live chat is STARTING! Ask your Qs about memory loss using #AskDrNancy. And join the conversation here: http://bit.ly/145p78L
3163                               We'll be chatting with  about early Alzheimer's on Google+ at 9 a.m. ET. Join us here: http://bit.ly/145p78L #AskDrNancy
3166                       Oh - and you can RSVP here for the #AskDrNancy chat, happening live on Tuesday at 9 a.m. ET. See you then! http://bit.ly/145p78L
3167                           Got a question for  on early Alzheimer's? Ask it with the hashtag #AskDrNancy, and she may answer tomorrow in a Google chat.
3610                                                                          Runners unite in online movement to #runforBoston http://on.today.com/15iN5h7
3658                                                 'Reasons my son is crying' makes parents weep... with mirth http://sfy.co/p4B0 #storify #parentingfail
3659                               You've been quoted in my #Storify story "'Reasons my son is crying' makes parents weep... with mirth" http://sfy.co/p4B0
3737                                    You've been quoted in my #Storify story "Friends and strangers react to Jenna Wolfe's baby news" http://sfy.co/bGHK
3738                                    You've been quoted in my #Storify story "Friends and strangers react to Jenna Wolfe's baby news" http://sfy.co/bGHK

In [ ]:
#remove '#' symbol from all entries
def remove_hash(text):
  return re.sub(r'#', '', text)

df[2] = df[2].apply(remove_hash)

example_with_hash = df[df[2].str.contains('#')]
example_with_hash #should be emtpy

Empty DataFrame
Columns: [2]
Index: []

In [ ]:
example_with_url = df[df[2].str.contains('http')]
example_with_url

                                                                                                                                                                                       2
0                                                                                                                   Ebola Exposure?: CDC Worker 'Remains Well' http://nbcnews.to/1tmYMkv
1                                                                                                             Pregnant Woman Taken Off Life Support in Ireland http://nbcnews.to/1BcYvPG
2                                                  Money from IceBucketChallenge still flowing to ALS Association where leaders remain awestruck by gush of goodwill: http://ow.ly/GseY3
3                                                                                                                Caramel Apples Recalled After Listeria Deaths http://nbcnews.to/1EqpPjj
4                                                                                                                Ice Bucket Challenge Still Rains Bucks on ALS http://nbcnews.to/1thdMAd
5                                                    Following mistake and possible exposures at CDC Ebola lab, health of involved staff to be monitored for 21 days. http://ow.ly/GpzmS
6                                                                                                       CDC Reports Possible Ebola Exposure at Containment Lab http://nbcnews.to/1CLABvX
7                                                                                                                Why Stress-Fueled Indulgences Don't Bring Joy http://nbcnews.to/1vbYiYB
8                                                                                                                   Delayed Concussions? 'Common' and 'Tricky' http://nbcnews.to/1EdtTDx
9                                                                                                     Gay Groups Decry FDA Rule Requiring No Sex to Give Blood http://nbcnews.to/1zgmtY8
10                                                                                                         FDA Plans to Ease Ban on Blood Donations by Gay Men http://nbcnews.to/1CDgVKG
11                                                                                                       FDA Proposes Easing Ban on Blood Donations by Gay Men http://nbcnews.to/1zuy6Qa
12                                                                                                               Nearly 2 Million More People Choose ObamaCare http://nbcnews.to/13BkCEA
13                                                                                             Beyond Narcan: Why the Life-Saving Heroin Antidote Isn't a Cure http://nbcnews.to/16NjUWM
14                                                                                                   Joan Lunden: 'I Can See the Finish Line' in Cancer Battle http://nbcnews.to/1ztxbzv
15                                                                                                   Joan Lunden: 'I Can See the Finish Line' In Cancer Battle http://nbcnews.to/1ADCoE6
16                                                                                                      Deadly 2015: Can Ebola's Rampage in Africa Be Stopped? http://nbcnews.to/1B17DXv
17                                                                                                     Boy With Rare Disease Donates His Toys to UCLA Hospital http://nbcnews.to/1B0cRTp
18                                                                                          Secrets From World's Oldest Yoga Teacher: 'I Don't Believe in Age' http://nbcnews.to/1t22uzR
19                                                                                                    Obamacare by the Numbers: What a Difference a Year Makes http://nbcnews.to/1znY0Fm
20                                                                                                    California Gets Worst Whooping Cough Outbreak in Decades http://nbcnews.to/1AMM1yo
21                                                                                                           Aging Tsunami: As Crisis Grows, a Search for Help http://nbcnews.to/1x90YgE
22                                                                                                           What's This 104-Year-Old's Formula for Longevity? http://nbcnews.to/13rkdob
23                                                                                                      Star Goalie's New Role Inspires Others With Tourette's http://nbcnews.to/1z8qKg6
24                                                                                                              How One Woman Makes a Difference Against Ebola http://nbcnews.to/1CncO5i
25                                                                                                       Aging Tsunami: Montana's Aging Crisis Takes a Village http://nbcnews.to/1AqCGOg
26                                                                                                                                   Flu Cases Surge in the US http://nbcnews.to/1wOCXJS
27                                                                                                     Meet Four People Who Lost 100 Pounds -- and Kept It Off http://nbcnews.to/1wyA1kF
28                                                                                                          Flu Season Is Off to an Early Start This Year: CDC http://nbcnews.to/1C9CKEm
29                                                                                                              Caramel Apples Linked to Five Deaths, CDC Says http://nbcnews.to/1Gz4YrQ
30                                                                                                                 Caramel Apples Linked to 5 Deaths, CDC Says http://nbcnews.to/1zFqgku
31                                                                                                                      Could Christmas Worsen Ebola's Spread? http://nbcnews.to/1H04M3c
32                                                                                                        That Cheap Old Car Might Carry Deadly Cost for Teens http://nbcnews.to/1zCSIoa
33                                                                                                                 One More Drug For Ebola Treatment Pipeline? http://nbcnews.to/1zCSJIP
34                                                                                                               Could Ibuprofen Extend Lives for Humans, Too? http://nbcnews.to/1GvQOYp
35                                                                                                              Baby Has 'Worst Disease You've Never Heard Of' http://nbcnews.to/13fPjPk
36                                                                                                                 Air Pollution May Nearly Double Autism Risk http://nbcnews.to/13eeS3x
37                                                                                                    New Stroke Treatment: Removing Clot Can Limit Disability http://nbcnews.to/1zxmFF4
38                                                                                                  103-Year-Old Doctor on Longevity: 'Exercise is Over-rated' http://nbcnews.to/1w0qaPx
39                                                                                                      Feds File Murder Charges in Fungal Meningitis Outbreak http://nbcnews.to/1J3vHz5
40                                                                                                          Smartphone Controlled Hands Offer Assisted Control http://nbcnews.to/1GQv1ZY
41                                                                                                   Transgender Teacher on Joy, Heartbreak of Life as a Woman http://nbcnews.to/1wL1iz3
42                                                                                                                    Yes, You Lose Weight by Breathing: Study http://nbcnews.to/1DMWm2J
43                                                                                                          Arrests Made in Meningitis Outbreak That Killed 60 http://nbcnews.to/1vYZuOU
44                                                                                                  Children's Cartoons Are Rife With Death and Murders: Study http://nbcnews.to/1vXHpki
45                                                                                                  Children's Cartoons Are Rife With Death and Murders: Study http://nbcnews.to/1DJT7t8
46                                                                                                            Children's Cartoons Are Rife With Murders: Study http://nbcnews.to/1BUrMj7
47                                                                                                      Most U.S. Doctors Now Support Assisted Suicide: Survey http://nbcnews.to/1ADA4KZ
48                                                                                                       Mind-Controlled Robot Arm Wins at Rock-Paper-Scissors http://nbcnews.to/1A7R4eb
49                                                                                                         'Strong Start': Millions More Sign Up for Obamacare http://nbcnews.to/1z0NVOp
50                                                                                                      Never Too Young: Seeking an Early Test for Alzheimer's http://nbcnews.to/1wHXiPy
51                                                                                                         FDA Warns Against Ultrasounds for 'Keepsake' Images http://nbcnews.to/1wHa2G8
52                                                                                                          U.S. Kids Favor E-Cigarettes Over Traditional Ones http://nbcnews.to/1sA9lAq
53                                                                                                 Mother of Surprise Quads: 'Luckiest Mom in the Whole World' http://nbcnews.to/1wW0MkP
54                                                                                                         New Test Detects Heart Disease Risk for Black Women http://nbcnews.to/1zpmI5B
55                                                                                                  Not Just Skin Cancer: Indoor Tanning Sends Hundreds to ERs http://nbcnews.to/1AA0EEL
56                                                                                                       Angelina Jolie's Chickenpox Can Be Serious for Adults http://nbcnews.to/1ySA9It
57                                                                                                     What's Wrong With Wyatt? Baby's Disease Baffles Parents http://nbcnews.to/12V64zq
58                                                                                                        Toddler Finally Hears Mom's Voice, Thanks To Implant http://nbcnews.to/1ITw4Mk
59                                                                                                          Misinformed: Prenatal Tests Have High Failure Rate http://nbcnews.to/12PVERq
60                                                                                                         Single Ebola Outbreak Gives Deadly Disease New Life http://nbcnews.to/1DrnVP4
61                                                                                                                                  Food to Help Fight the Flu http://nbcnews.to/16gczPk
62                                                                                                                  ThisTown May Hold the Secrets of Longevity http://nbcnews.to/1uv1MVu
63                                                                                                            'Dude, Watch This!' Are men really more idiotic? http://nbcnews.to/1yF1MJW
64                                                                                                            Nurse on Trial: Force-Feeding Case at Guantanamo http://nbcnews.to/1uqX6jt
65                                                                                                                   Joint Pain Interrupts Ebola Vaccine Trial http://nbcnews.to/1vW2Sz6
66                                                                                                            Once Obese But Starving Girl Sees Healthy Future http://nbcnews.to/12Sggbm
67                                                                                                                 Burning the Candle: Most US Kids Lack Sleep http://nbcnews.to/1wE7An7
68                                                                                                         Breast Cancer Prevention Last Decades, Studies Find http://nbcnews.to/1us90dY
69                                                                                                                   U.S. Nurse Being Watched at NIH for Ebola http://nbcnews.to/16aBIuy
70                                                                                                 'Biggest Loser' Trainer on How to Avoid Holiday Weight Gain http://nbcnews.to/169Wr1y
71                                                                                                       Bad Luck: Men With Poor Semen Have Poorer Health, Too http://nbcnews.to/1AhrYaT
72                                                                                                                  New HPV Vaccine Broadens Cancer Protection http://nbcnews.to/1wel2vP
73                                                                                                           Phthalates in Food Packaging Linked With Lower IQ http://nbcnews.to/1GdWhmy
74                                                                                                           Phthalates in Food Packaging Linked With Lower IQ http://nbcnews.to/1z7zdTr
75                                                                                                 Breast Cancer Patients May Get Longer Radiation Than Needed http://nbcnews.to/1IAYevF
76                                                                                                  Too Much Radiation? Women Could Get Less for Breast Cancer http://nbcnews.to/1wguqhm
77                                                                                                      High Risk: 100-Fold Ebola Rate for Health Care Workers http://nbcnews.to/1zLGVlm
78                                                                                                      Huge Ebola Risk Faces Sierra Leone Health Care Workers http://nbcnews.to/134p9j7
79                                                                                                           Could the Chemical BPA Raise Your Blood Pressure? http://nbcnews.to/12jzZAW
80                                                                                                               Childhood Illness Fells Mighty Hockey Players http://nbcnews.to/12YHKNu
81                                                                                                    Billionaire Paul Allen Pledges Millions for Cell Science http://nbcnews.to/1yIcuhF
82                                                                                '20/20 Hindsight': Doc Who Sent Ebola Patient Home Says Care Was Appropriate http://nbcnews.to/1yt1rFi
83                                                                                                                    Ebola 'Czar' to Return to Private Sector http://nbcnews.to/1ysGSsy
84                                                                                                        Want an Easy, Healthy Breakfast? Try These 3 Recipes http://nbcnews.to/12zJ6NI
85                                                                                                           Obama Visits Walter Reed Hospital For Sore Throat http://nbcnews.to/1wcQZ9y
86                                                                                                  Oxygen Therapy or Hot Air? Treatment Doesn't Pass the Test http://nbcnews.to/1q7Dy8h
87                                                                                                  Oxygen Therapy or Hot Air? Treatment Doesn't Pass the Test http://nbcnews.to/1wb4ruD
88                                                                                                   Testing for an Incurable Disease: Would You Want to Know? http://nbcnews.to/1vpKh9x
89                                                                                                                Use of Unproven Stem Cell Therapy Questioned http://nbcnews.to/1zwjrk5
90                                                                                                                Is 'Technoference' Hurting Your Relationship http://nbcnews.to/1yw6VTl
91                                                                                                                 This Season's Flu Vaccine Is Less Effective http://nbcnews.to/1yYc5HR
92                                                                                                                   Mutant Flu: Do You Still Need a Vaccine?  http://nbcnews.to/1yXb42M
93                                                                                                                    Y Quit? Smoking Destroys Male Chromosome http://nbcnews.to/1yXb2Ie
94                                                                                                                     Whooping Cough Epidemic? Get Used to It http://nbcnews.to/1vS2Ojt
95                                                                                                         Why Bother Getting Flu Shot? What You Need to Know  http://nbcnews.to/1zWpiiC
96                                                                                                             Dallas Spent $27K to Care for Ebola Nurse's Dog http://nbcnews.to/1I59osd
97                                                                                     Young Cancer Patients Benefit From More Teen-Friendly Treatment Centers http://nbcnews.to/1yVJzX8
98                                                                                                   CDC Warning: Flu Viruses Mutate and Evade Current Vaccine http://nbcnews.to/1tH4CHC
99                                                                                                          'Unprecedented': Drug May Help Heal Damaged Spines http://nbcnews.to/1yRvoCt
100                                                                                                 Terminally Ill Basketball Player Signs Up for Hospice Care http://nbcnews.to/1yRvpWZ
101                                                                                                        Growth in U.S. Health Spending the Lowest On Record http://nbcnews.to/1tO0CV1
102                                                                                                     Obamacare Bump: 10 Million Got Insurance, Survey Shows http://nbcnews.to/1yOq4yU
103                                                                                                             New Labels to Clarify Prescribing in Pregnancy http://nbcnews.to/1zRebaB
104                                                                                                         IBM Helps You Donate Computer Power to Fight Ebola http://nbcnews.to/1vjzrBJ
105                                                                                                                   Divorce Rates Are Lower in the U.S. Why? http://nbcnews.to/1HZHrSH
106                                                                                                 Dr. Nancy Snyderman 'Sorry' For Violating Ebola Quarantine http://nbcnews.to/1yKH1dv

In [ ]:
#remove urls
def remove_url(text):
  url_pattern = r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
  return re.sub(url_pattern, '', text)

df[2] = df[2].apply(remove_url)
df.loc[2766, 2] = df.loc[2766, 2].replace('http:', '', 1)
example_with_url = df[df[2].str.contains('http')]
example_with_url #should be empty

Empty DataFrame
Columns: [2]
Index: []

In [ ]:
#convert all to lowercase
df[2] = df[2].str.lower()
df.head(10)

                                                                                                                     2
0                                                                          ebola exposure?: cdc worker 'remains well'
1                                                                    pregnant woman taken off life support in ireland
2  money from icebucketchallenge still flowing to als association where leaders remain awestruck by gush of goodwill:
3                                                                       caramel apples recalled after listeria deaths
4                                                                       ice bucket challenge still rains bucks on als
5    following mistake and possible exposures at cdc ebola lab, health of involved staff to be monitored for 21 days.
6                                                              cdc reports possible ebola exposure at containment lab
7                                                                       why stress-fueled indulgences don't bring joy
8                                                                          delayed concussions? 'common' and 'tricky'
9                                                            gay groups decry fda rule requiring no sex to give blood

In [ ]:
#add columns called "centroid" and "error" to df
df['centroid'] = 0
df['error'] = 0
df.head()
#rename column '2' to 'tweet'
df = df.rename(columns={2: 'tweet'})
df.head()

,tweet,centroid,error
0,ebola exposure?: cdc worker 'remains well',0,0
1,pregnant woman taken off life support in ireland,0,0
2,money from icebucketchallenge still flowing to als association where leaders remain awestruck by gush of goodwill:,0,0
3,caramel apples recalled after listeria deaths,0,0
4,ice bucket challenge still rains bucks on als,0,0

In [ ]:
def initialize_centroids(data, k):
  centroids = data.sample(n=k, random_state = 0)
  return centroids

#distance = 1 - (intersect of A, B)/ (union of A, B)
def calculate_distance(a, b):
  a_words = a.split()
  b_words = b.split()
  a_int_b = len(set(a_words).intersection(b_words))
  a_union_b = len(set(a_words).union(b_words))

  return 1 - (a_int_b / a_union_b)

#assign observation to closest centroid
def assign_clusters(data, centroids):
  k = centroids.shape[0]
  n = data.shape[0]
  clusters = []
  assign_errors = []

  for i in range(n):
    all_errors = np.array([])
    for centroid in range(k):
      error = calculate_distance(centroids.iloc[centroid]['tweet'], df.iloc[i]['tweet'])
      all_errors = np.append(all_errors, error)
    nearest_cluster = np.where(all_errors==np.amin(all_errors))[0].tolist()[0]
    nearest_cluster_error = np.amin(all_errors)
    clusters.append(nearest_cluster)
    assign_errors.append(nearest_cluster_error)
  return clusters, assign_errors

In [ ]:
centroids = initialize_centroids(df, 5)
centroids.iloc[0:,0]

2594                 opinion: why selling kidneys still won't work
1246    kids with rare disease may hold secret to stopping viruses
2337          obama says health care website will get fixed asap
678            fda urges restaurants and consumers to cut the salt
2933                           obamacare 'affordable?' some say no
Name: tweet, dtype: object

In [ ]:
#k-means algo

#randomly assign centroid for each
centroids = initialize_centroids(df, 235)
initial_centroid_tweets = centroids['tweet'].copy()
loop = True
tot_err = []
while loop:

  #find new location of the centroid by taking mean of all the observations in each cluster
  df['centroid'], df['error'] = assign_clusters(df, centroids)
  tot_err.append(sum(df['error']))

  centroids = df.groupby('centroid').agg({'tweet': 'first','error': 'mean'})
  centroids = centroids.reset_index(drop = True)

  if len(tot_err) > 1:
    if tot_err[len(tot_err)-1] - tot_err[len(tot_err)-2] <= 1e-4:
      loop = False

centroids

,tweet,error
0,ice bucket challenge still rains bucks on als,0.957662
1,boy with rare disease donates his toys to ucla hospital,0.812163
2,high risk: 100-fold ebola rate for health care workers,0.808696
3,why my husband and i sleep apart,0.832594
4,"violence against women 'unacceptably high,' experts say",0.855801
5,caramel apples recalled after listeria deaths,0.894212
6,children's cartoons are rife with death and murders: study,0.694573
7,how many calories in a thanksgiving feast?,0.874224
8,texting neck: hunching over your phone stresses your spine,0.423077
9,beyond narcan: why the life-saving heroin antidote isn't a cure,0.751743
10,u.s. kids favor e-cigarettes over traditional ones,0.888756
11,while i was sleeping: confessions of an ambien zombie,0.789711
12,mini-stomachs let scientists study ulcers in a lab dish,0.790572
13,'20/20 hindsight': doc who sent ebola patient home says care was appropriate,0.803760
14,allergic to penicillin? you're probably not,0.900648
15,fda plans to ease ban on blood donations by gay men,0.800008
16,woman whose 'real' bikini pic went viral gets magazine shoot,0.314103
17,smartphone controlled hands offer assisted control,0.860235
18,"want an easy, healthy breakfast? try these 3 recipes",0.621418
19,boy born without thumbs gets hands transformed,0.826707
20,billionaire paul allen pledges millions for cell science,0.433333
21,oxygen therapy or hot air? treatment doesn't pass the test,0.540441
22,joint pain interrupts ebola vaccine trial,0.769100
23,ebola mappers track epidemic in real time,0.775816
24,report: paralyzed man walks after nerve cell transplant,0.747529
25,"bankers' culture may encourage cheating, study finds",0.838538
26,scientists discover 'blonde gene',0.616667
27,"circumcision benefits outweigh the risks, cdc says",0.849444
28,aging tsunami: montana's aging crisis takes a village,0.737179
29,childhood illness fells mighty hockey players,0.731136
30,secrets from world's oldest yoga teacher: 'i don't believe in age',0.577451
31,what's this 104-year-old's formula for longevity?,0.902461
32,deadly stigma: why lung cancer is killing more non-smokers,0.837377
33,breast cancer patients may get longer radiation than needed,0.779694
34,ibm helps you donate computer power to fight ebola,0.707143
35,"face, limb transplants allocated like other organs",0.464286
36,"did you hear? gossip can be good for you, study says",0.820206
37,"toddler finally hears mom's voice, thanks to implant",0.790030
38,one more drug for ebola treatment pipeline?,0.813324
39,headed for disaster: what we know about traumatic brain injury,0.820394
40,why bother getting flu shot? what you need to know,0.764401
41,hickox: frustrated nursing school turned away boyfriend,0.740000
42,a tale of two outbreaks: why congo conquered ebola,0.776500
43,"world aids day: aids activists, the new feminists?",0.831799
44,nyc 'actively monitoring' 117 people for ebola risk,0.724477
45,what does surgeon's death teach us about treating ebola?,0.788378
46,ebola czar's first day: meeting white house teams,0.809519
47,oh boy! couple with 12 sons expecting baby no. 13,0.775996
48,asknbcnews: fort hood shooting webcast,0.733618
49,docs cringe at radio jock's c-section suggestion,0.461538
50,meet four people who lost 100 pounds -- and kept it off,0.776546
51,montana clinic helps with a 'special delivery',0.864206
52,cdc: anthrax exposure resulted from breakdown in safety protocol via,0.577778
53,u.k. mom opts to end life of disabled child,0.861552
54,star goalie's new role inspires others with tourette's,0.696667
55,grieving family hears son's heart beat in another's chest,0.762665
56,obama to praise u.s. ebola efforts,0.797776
57,watch live: dallas nurses hold briefing on ebola care,0.859413
58,never too young: seeking an early test for alzheimer's,0.799299
59,8 percent of americans have depression but few are treated,0.803748
60,new stroke treatment: removing clot can limit disability,0.817004
61,how does that happen? preemie twins born 39 days apart,0.633406
62,new hpv vaccine broadens cancer protection,0.872188
63,that cheap old car might carry deadly cost for teens,0.647470
64,vision quest: stem cells treat blinding disease,0.804989
65,"florida woman, 46, sets record for birth via ivf",0.761560
66,'abundance of politics': ebola nurse slams christie,0.869696
67,u.s. names 35 ebola-certified hospitals,0.834110
68,bite club: what makes luis suarez chomp?,0.433333
69,'bionic pancreas' astonishes diabetes researchers,0.819394
70,single ebola outbreak gives deadly disease new life,0.828208
71,103-year-old doctor on longevity: 'exercise is over-rated',0.681535
72,viral baby announcement includes cookies and screams,0.826937
73,fda reconsiders ban on gays donating blood,0.851062
74,"transgender teacher on joy, heartbreak of life as a woman",0.816337
75,"sister finds brother shirtless, dead in snow",0.783450
76,snooze or lose: tips for getting a good night's sleep,0.726195
77,could this plane help save ebola patients?,0.767349
78,tiny sip of beer enough to trigger dopamine release,0.000000
79,sweet! special cocoa drink may reverse memory loss,0.910106
80,can being a cop kill you? study finds biggest heart risks,0.803543
81,is 'technoference' hurting your relationship,0.880786
82,blind man struck by subway says dog 'saved my life',0.585784
83,defective cochlear implants shocked kids - even after warnings,0.423077
84,'gave it everything': doctors discuss death of ebola patient,0.760495
85,flu season is off to an early start this year: cdc,0.802194
86,"hospital errors drop, saving 50,000 lives: government",0.610723
87,ebola exposure?: cdc worker 'remains well',0.795496
88,former nfl lineman: 'my kidneys got progressively worse every year',0.000000
89,mutant flu: do you still need a vaccine?,0.838654
90,maynard's death: why is brain cancer so lethal?,0.810013
91,"not ripped like spiderman? boys have body image woes, too",0.754798
92,breakthrough? nose spray ebola vaccine protects monkeys,0.680952
93,pregnant woman taken off life support in ireland,0.887545
94,air pollution may nearly double autism risk,0.753005
95,obamacare by the numbers: what a difference a year makes,0.807178
96,dr. nancy snyderman 'sorry' for violating ebola quarantine,0.799974
97,women bosses more prone to depression: study,0.833496
98,"rt : yuck! rt : vacationer beware: hot tubs, pools may harbor many germs",0.751817
99,feds file murder charges in fungal meningitis outbreak,0.798507
100,mom's hand-made disney costumes help shy girl blossom,0.599359
101,"could ibuprofen extend lives for humans, too?",0.691049
102,bad credit linked to higher heart attack risk,0.791426
103,not just skin cancer: indoor tanning sends hundreds to ers,0.688039
104,health spending set to start growing faster,0.853800
105,gay groups decry fda rule requiring no sex to give blood,0.719389
106,holiday surprise: what to do when mom or dad is slipping away,0.815832
107,"most u.s. babies sleep in unsafe conditions, report finds",0.814207
108,"ebola epidemic not even close to over, un officials say",0.761503
109,fda warns against device it says can spread cancer,0.826340
110,mind-controlled robot arm wins at rock-paper-scissors,0.870812
111,"girl athletes need training to protect knees, doctors advise",0.748478
112,rt : tales of chucking big jobs are the new lady porn rt : what's really causing women to burn out before 30:,0.852535
113,ashoka mukpo statement: 'today is a joyful day',0.714920
114,huggies heist: diaper bank robbers lift 13k load,0.000000
115,every last penny: the booming funeral business,0.594444
116,growth in u.s. health spending the lowest on record,0.817651
117,ebola health sleuths seek ohio bridal shop customers,0.647619
118,new brittany maynard video calls for action,0.742069
119,10 moms tell us why they choose home over work,0.596491
120,"breast cancer prevention last decades, studies find",0.840771
121,why pregnancy doesn't keep me from running,0.870396
122,'incredible gift': man thankful for double arm transplant,0.797268
123,money from icebucketchallenge still flowing to als association where leaders remain awestruck by gush of goodwill:,0.792526
124,testing for an incurable disease: would you want to know?,0.753603
125,"pizza, popcorn included in new fda calorie label rules",0.797046
126,cdc backtracks: illinois man didn't have mers after all,0.739174
127,"as ebola scare hit dallas, residents hunkered down",0.834619
128,why stress-fueled indulgences don't bring joy,0.899874
129,is arkansas gov. a snowplow parent for pardoning son?,0.787001
130,'strong start': millions more sign up for obamacare,0.821722
131,"bye, barefoot runners: fat-soled shoes may protect aging joints",0.879761
132,'million dollar question': why can't we sleep?,0.743537
133,nearly 2 million more people choose obamacare,0.825523
134,a death a minute 30 years after the union carbide disaster,0.764722
135,5 million strollers recalled over fingertip amputations,0.780362
136,baby has 'worst disease you've never heard of',0.464286
137,"aging tsunami: as crisis grows, a search for help",0.784067
138,most u.s. doctors now support assisted suicide: survey,0.739711
139,unhealthy or simply skinny? yale student shares bmi ordeal,0.620635
140,hidden cure? how people with 'ebola-proof' blood could save lives,0.720158
141,how one woman makes a difference against ebola,0.755810
142,seventh grader facing blindness aims to help others see,0.552047
143,"following mistake and possible exposures at cdc ebola lab, health of involved staff to be monitored for 21 days.",0.876326
144,calling it quits: american smoking hits 50 year low,0.766325
145,eight women die after sterilization surgery in india,0.808191
146,who's in charge of america's battle against ebola?,0.810761
147,'we're ready to go': ebola-stricken surgeon lands in u.s.,0.754525
148,delayed concussions? 'common' and 'tricky',0.870924
149,hiv patients getting sicker to qualify for housing,0.813717
150,most people allergic to penicillin are not: researchers,0.830299
151,"bad luck: men with poor semen have poorer health, too",0.658088
152,"home cooks eat better, new study finds",0.812673
153,california gets worst whooping cough outbreak in decades,0.728665
154,"kids' school plays are painful, louis c.k. jokes on 'snl'",0.441176
155,"ryan reynolds, michael j. fox team up on parkinson's",0.428571
156,today's geist and daly undergo live testicular exams,0.832544
157,"summer bummer: when school's out, kids put on pounds",0.794844
158,watch live: bilateral arm transplant news conference,0.636974
159,is it safe to eat tuna fish every day?,0.733921
160,scrubs go high-tech,0.734921
161,liberia suspends election campaigning over ebola,0.831510
162,food to help fight the flu,0.855157
163,"what, me fat? most americans don't think so, poll finds",0.764824
164,how well do hotel maids really clean?,0.764207
165,could watching tv kill you?,0.844443
166,startup launches 'first wearable health record' for google glass,0.433333
167,terminally ill basketball player signs up for hospice care,0.628571
168,'no room for optimism': who reports some ebola progress,0.756908
169,e. coli outbreak is over after big beef recall,0.699140
170,the hidden downsides of a gluten-free diet,0.821289
171,"couch potato today, wheelchair tomorrow? study links sitting, disability",0.000000
172,older mom? you may live longer,0.821512
173,could christmas worsen ebola's spread?,0.000000
174,joan lunden: 'i can see the finish line' in cancer battle,0.656483
175,"22 pens, 47 million americans: obamacare by the numbers",0.641667
176,u.s. nurse being watched at nih for ebola,0.805995
177,ebola gives west africans temporary respite in u.s.,0.728993
178,'zoning out really bad': narcolepsy video goes viral,0.757893
179,obamacare 2.0: new 2015 enrollment phase rolls out,0.622619
180,obama 'sure' he suffered concussions playing football,0.746703
181,'today i am healthy': ebola-stricken doctor leaves hospital,0.749391
182,defiant ebola nurse: i will not be 'bullied by politicians',0.781549
183,new labels to clarify prescribing in pregnancy,0.835862
184,'gave it everything': ebola-infected surgeon dies in nebraska,0.702091
185,whooping cough epidemic? get used to it,0.821898
186,why a clean home could mean a clean conscience,0.748436
187,"when food isn't enough: gut bugs affect malnutrition, too, study finds",0.530702
188,ebola 'czar' to return to private sector,0.805227
189,misinformed: prenatal tests have high failure rate,0.694359
190,"fewer wrinkles, thinner arms: today anchors get photoshopped",0.561616
191,once obese but starving girl sees healthy future,0.615385
192,ebola death toll leaps higher,0.830574
193,cdc reassigns head of lab behind anthrax blunder,0.752538
194,"schools offer veggies for lunch, but most kids don't bite",0.785053
195,mom charged with killing autistic son 'heard voices',0.873109
196,the baby talk gap? moms may talk more to girls,0.776552
197,'unprecedented': drug may help heal damaged spines,0.783430
198,could the chemical bpa raise your blood pressure?,0.583639
199,"muffin top melting recipes: joy bauers's fiery popcorn, chocolate pudding, more",0.683978
200,phthalates in food packaging linked with lower iq,0.799841
201,spider-web bandages: new medicine mimics nature,0.458333
202,radicalized: who is prone to isis internet recruiting?,0.779997
203,4-year-old boy suffers mysterious strokes,0.721414
204,"yes, you lose weight by breathing: study",0.800954
205,ebola video game: training medics far from hazard,0.644872
206,4 stroke symptoms to watch for,0.782473
207,9 simple questions that may predict heart disease or cancer risk,0.728817
208,bird flu forces church to hold drive-in service,0.803261
209,oklahoma gov. orders review of execution protocols,0.428571
210,deadly 2015: can ebola's rampage in africa be stopped?,0.780513
211,burning the candle: most us kids lack sleep,0.768467
212,fda warns against ultrasounds for 'keepsake' images,0.801185
213,flu cases surge in the us,0.862907
214,new test detects heart disease risk for black women,0.764458
215,feds to take over oregon's broken health exchange,0.825907
216,"peer pressure lasts only three days, study says",0.722451
217,less painful mammograms? new device may help,0.777072
218,how high are your goosebumps? new technology tells,0.762961
219,cdc reports possible ebola exposure at containment lab,0.864716
220,tick spit is the newest weapon in the fight against cancer,0.788646
221,use of unproven stem cell therapy questioned,0.769882
222,'biggest loser' trainer on how to avoid holiday weight gain,0.827909
223,ebola kills nurse in mali and worse spread is feared,0.755209
224,y quit? smoking destroys male chromosome,0.761386
225,autism advocates welcome seinfeld's disclosure,0.609654
226,"'dude, watch this!' are men really more idiotic?",0.773797
227,doctor on ebola death: 'we weren't able to get him through this',0.794358
228,nurse on trial: force-feeding case at guantanamo,0.817235
229,"uv nail salon lights could trigger cancer, study says",0.758036
230,6 things my 'adoptive' parents did right,0.792192
231,fertility pause helps women have babies after chemo,0.612302
232,thistown may hold the secrets of longevity,0.773283
233,thousands of children at risk from laundry pods: study,0.813173
234,can a class shake off the effects of social media?,0.781224
235,fda proposes easing ban on blood donations by gay men,0.713910

In [ ]:
#SSE
#sum squarred error for each centroid
error_per_cluster = df.groupby('centroid')['error'].sum()
print(error_per_cluster)
#sum error of error_per_cluster
print("SSE: " + str(error_per_cluster.sum()))

centroid
0       30.645173
1       20.304081
2       33.156554
3       19.982268
4       27.385648
5       55.441126
6        9.724016
7       73.434796
8        0.846154
9        6.765687
10      21.330152
11       5.527976
12      10.277442
13      17.682716
14      81.058353
15      12.800131
16       0.942308
17      12.903530
18       1.864253
19       9.093777
20       0.866667
21       2.702206
22      12.305594
23       8.533974
24       8.970349
25      74.629916
26       1.850000
27      32.278891
28       3.685897
29       3.655682
30       1.732353
31      63.172251
32      20.097059
33      14.034485
34       4.242857
35       0.928571
36      23.785969
37       6.320238
38      25.213054
39      14.767088
40      16.816832
41       3.700000
42       7.764998
43      16.635984
44       5.071337
45       8.672158
46      10.523745
47       8.535958
48       4.401709
49       0.923077
50       5.435825
51      23.333562
52       1.733333
53      62.031719
54       3.483333
55       7.626648
56      22.337726
57      20.625900
58      12.788782
59      11.252475
60       9.804047
61       2.533626
62      47.098127
63       2.589881
64      12.074829
65       5.330920
66      38.266625
67      10.009314
68       0.866667
69       8.193939
70      19.877004
71       3.407673
72       8.269368
73      22.127606
74      16.326740
75       8.617949
76       5.809559
77       8.440836
78       0.000000
79      46.415385
80      17.677954
81      44.920082
82       1.757353
83       0.846154
84      20.533377
85      16.846078
86       1.832168
87      12.727939
88       0.000000
89      20.966340
90      10.530170
91       4.528789
92       2.723810
93      58.577957
94       6.024043
95      16.143551
96      19.999348
97      44.175304
98       4.510902
99      18.365664
100      1.798077
101      3.455245
102     23.742789
103      3.440196
104     30.736817
105      3.596943
106     13.869143
107     23.611993
108      9.899533
109     18.179482
110     15.674613
111      5.987821
112     17.050696
113      7.864123
114      0.000000
115      1.783333
116     36.794296
117      2.590476
118      6.678621
119      1.789474
120     22.700814
121     15.667125
122     10.364485
123      7.132733
124      7.536029
125     51.807994
126      5.174219
127     10.850046
128     59.391712
129      7.870011
130     30.403701
131     22.873776
132      5.204762
133     24.765692
134      6.117776
135      7.023260
136      0.928571
137     10.192869
138      5.177976
139      1.861905
140      5.041106
141      6.046479
142      1.656140
143     19.279180
144      5.364275
145     14.547436
146     68.914700
147      8.299771
148     16.547557
149     22.784066
150     15.775688
151      2.632353
152     64.201159
153      6.557986
154      0.882353
155      0.857143
156     20.813602
157      9.538126
158      3.821845
159      6.605289
160      3.674603
161     14.967172
162    107.749737
163      8.413067
164      5.349451
165     10.977756
166      0.866667
167      2.514286
168      6.055264
169      3.495700
170     31.208965
171      0.000000
172     14.787218
173      0.000000
174      5.908346
175      2.566667
176     16.119909
177      7.289927
178      6.063145
179      2.490476
180      4.480220
181      6.744522
182      7.033940
183     61.853757
184      7.020906
185     24.656945
186      7.484360
187      1.592105
188     17.714985
189      3.471795
190      1.684848
191      1.846154
192     14.950327
193      5.267766
194      7.850535
195     20.954612
196     13.201380
197      7.834299
198      1.750916
199      2.735913
200     19.196191
201      0.916667
202      8.579972
203      3.607071
204      8.009536
205      2.579487
206     10.954623
207      5.101716
208     20.884790
209      0.857143
210      8.585644
211      6.916205
212     16.023701
213    130.298933
214     10.702413
215     27.254933
216      4.334707
217     10.101933
218      6.866652
219     51.018257
220     12.618329
221      6.928938
222     18.214002
223      7.552086
224      4.568315
225      3.657925
226      7.737966
227     10.326651
228     13.075757
229      6.064286
230      6.337537
231      4.898413
232     10.825966
233     23.582005
234      7.031020
235      4.283462
Name: error, dtype: float64
SSE: 3441.258673790291

In [ ]:
#show centroid 8
pd.set_option('display.max_colwidth', None)
df[df['centroid'] == 8]

,tweet,centroid,error
172,texting neck: hunching over your phone stresses your spine,8,0.000000
176,study reveals texting puts pressure on spine,8,0.846154

In [ ]:
#size f each cluster
#print full list
pd.set_option('display.max_rows', None)
print(df.groupby('centroid').size())

centroid
0       32
1       25
2       41
3       24
4       32
5       62
6       14
7       84
8        2
9        9
10      24
11       7
12      13
13      22
14      90
15      16
16       3
17      15
18       3
19      11
20       2
21       5
22      16
23      11
24      12
25      89
26       3
27      38
28       5
29       5
30       3
31      70
32      24
33      18
34       6
35       2
36      29
37       8
38      31
39      18
40      22
41       5
42      10
43      20
44       7
45      11
46      13
47      11
48       6
49       2
50       7
51      27
52       3
53      72
54       5
55      10
56      28
57      24
58      16
59      14
60      12
61       4
62      54
63       4
64      15
65       7
66      44
67      12
68       2
69      10
70      24
71       5
72      10
73      26
74      20
75      11
76       8
77      11
78       1
79      51
80      22
81      51
82       3
83       2
84      27
85      21
86       3
87      16
88       1
89      25
90      13
91       6
92       4
93      66
94       8
95      20
96      25
97      53
98       6
99      23
100      3
101      5
102     30
103      5
104     36
105      5
106     17
107     29
108     13
109     22
110     18
111      8
112     20
113     11
114      1
115      3
116     45
117      4
118      9
119      3
120     27
121     18
122     13
123      9
124     10
125     65
126      7
127     13
128     66
129     10
130     37
131     26
132      7
133     30
134      8
135      9
136      2
137     13
138      7
139      3
140      7
141      8
142      3
143     22
144      7
145     18
146     85
147     11
148     19
149     28
150     19
151      4
152     79
153      9
154      2
155      2
156     25
157     12
158      6
159      9
160      5
161     18
162    126
163     11
164      7
165     13
166      2
167      4
168      8
169      5
170     38
171      2
172     18
173      1
174      9
175      4
176     20
177     10
178      8
179      4
180      6
181      9
182      9
183     74
184     10
185     30
186     10
187      3
188     22
189      5
190      3
191      3
192     18
193      7
194     10
195     24
196     17
197     10
198      3
199      4
200     24
201      2
202     11
203      5
204     10
205      4
206     14
207      7
208     26
209      2
210     11
211      9
212     20
213    151
214     14
215     33
216      6
217     13
218      9
219     59
220     16
221      9
222     22
223     10
224      6
225      6
226     10
227     13
228     16
229      8
230      8
231      8
232     14
233     29
234      9
235      6
dtype: int64